my_snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: FKA50167  # e.g. abc12345.us-east-1
      user: DBTLABS_ECHAVEZ
      password: Snow_Flake90
      role: TRANSFORMER  # optional but recommended
      database: ANALYTICS
      warehouse: TRANSFORMING
      schema: DBT_ECHAVEZ
      threads: 4
      client_session_keep_alive: false