models:
  - name: dim_listings_cleansed
    columns:
     - name: listing_id
       tests:
         - unique
         - not_null

# this test does NOT allow any inserts in the dim_listings_cleansed.host_id 
# that do NOT exist in dim_hosts_cleansed.host_id
     - name: host_id
       tests:
         - not_null
         - relationships:
             field: host_id
             to: ref('dim_hosts_cleansed')
    
     - name: room_type
       tests:
         - accepted_values:
             values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']

     - name: minimum_nights
       tests:
        - positive_value