models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
     - name: listing_id
       description: Primary Key for the listing
       tests:
         - unique
         - not_null

# this test does NOT allow any inserts in the dim_listings_cleansed.host_id 
# that do NOT exist in dim_hosts_cleansed.host_id
     - name: host_id
       description: The host's id. References the host table
       tests:
         - not_null
         - relationships:
             field: host_id
             to: ref('dim_hosts_cleansed')
    
     - name: room_type
       description: Type of apartment or room
       tests:
         - accepted_values:
             values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']

     - name: minimum_nights
       description: '{{ doc("dim_listings_cleansed_minimum_nights") }}'
       tests:
        - positive_value